BE/Django/practice/day_5_20250328/django_ws_5_b/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login')
]

BE/Django/practice/day_5_20250328/django_ws_5_b/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('new_todo/', views.create, name='create'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
]

BE/Django/practice/day_5_20250328/django_ws_5_b/accounts/models.py
from django.db import models

# Create your models here.

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

BE/Django/practice/day_5_20250328/django_ws_5_b/accounts/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'accounts/login.html')

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

def create(request):
    todo = Todo()
    todo.work = request.POST.get('work')
    todo.content = request.POST.get('content')
    todo.is_completed = False
    
    todo.save()

    context = {
        'todo' : todo
    }
    return render(request, 'todos/detail.html', context)

def delete(request, todo_pk):
    todo = Todo.objects.get(pk = todo_pk)
    todo.delete()
    return redirect('todos:index')

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/templates/todos/create_todo.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>
  <form action="{% url "todos:create" %}" method="post">
    {% csrf_token %}
    <div>
      <label for="work">work : </label>
      <input type="text" name="work" id="work">
    </div>
    <div>
      <label for="content"> content : </label>
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <input type="submit" value="제출">
  </form>
{% endblock content %}

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/templates/todos/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 상세 페이지</h1>
  <hr>
  <p>{{ todo.pk }}번 째 할 일</p>
  <p>할 일 : {{ todo.work }}</p>
  <p>내 용 : {{ todo.content }}</p>
  <p>일 자 : {{ todo.created_at }}</p>
  <p>완 료 : {{ todo.is_completed }}</p>
  <hr>
  <form action="{% url "todos:delete" todo.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
{% endblock content %}

BE/Django/practice/day_5_20250328/django_ws_5_b/todos/templates/todos/index.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 관리 프로젝트 메인 페이지</h1>
  <p>이 곳에서 할 일 목록을 관리합니다.</p>
  <ul>
    {% for todo in todo_list %}
      <li>
        <a href="{% url "todos:detail" todo.pk %}">{{ todo.work }}</a>
        <p>{{ todo.is_completed }}</p>
      </li>
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}
  </ul>
{% endblock content %}