DB_study/practice/day_4_20250410/db_hw_4_4/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

DB_study/practice/day_4_20250410/db_hw_4_4/book_review_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libraries/', include('libraries.urls')),
    path('accounts/', include('accounts.urls'))
]

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/urls.py
from django.urls import path
from . import views


app_name = 'libraries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_pk>/', views.detail, name='detail'),
    path('<int:book_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:book_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

DB_study/practice/day_4_20250410/db_hw_4_4/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.title
    

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content',)

DB_study/practice/day_4_20250410/db_hw_4_4/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('libraries:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/views.py
from django.shortcuts import render, redirect
from .models import Book, Review
from .forms import ReviewForm

# Create your views here.
def index(request):
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'libraries/index.html', context)

def detail(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    book_form = ReviewForm()
    reviews = book.review_set.all()
    context = {
        'book': book,
        'form' : book_form,
        'reviews' : reviews,
    }
    return render(request, 'libraries/detail.html', context)

def comments_create(request, book_pk):
    book = Book.objects.get(pk = book_pk)
    comment_form = ReviewForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.book = book
        comment.user = request.user
        comment.save()
        return redirect('libraries:detail', book.pk)
    context = {
        'comment_form' : comment_form
    }
    return render(request, 'libraries/deatil.html', context)

def comments_delete(request, book_pk, comment_pk):
    comment = Review.objects.get(pk = comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('libraries:detail', book_pk)

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/templates/libraries/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>책 상세 정보</h1>
  <p>등록 번호 : {{ book.pk }}</p>
  <p>제목 : {{ book.title }}</p>
  <p>설명 : {{ book.description }}</p>
  <hr>
  <h2>리뷰 등록</h2>
  {% if user.is_authenticated %}
  <form action="{% url "libraries:comments_create" book.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="리뷰 작성">
  </form>
  {% else %}
  <p>로그인 후 작성해주세요.</p>
  {% endif %}
  <hr>
  <h2>리뷰 전체 목록</h2>
  {% for review in reviews %}
  <form action="{% url "libraries:comments_delete" book.pk review.pk %}" method="post">
    {% csrf_token %}
    <ul>
      <li>{{ review.user }} - {{ review.content }}</li>
      {% if review.user == user %}
      <input type="submit" value="리뷰 삭제">
      {% endif %}
    </ul>
  </form>
  {% endfor %}

  <a href="{% url "libraries:index" %}">[BACK]</a>
{% endblock content %}

DB_study/practice/day_4_20250410/db_hw_4_4/libraries/templates/libraries/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>책 전체 목록</h1>
  <ul>
    {% for book in books %}
      <a href="{% url 'libraries:detail' book.pk %}">
        <li>제목 : {{ book.title }}</li>
      </a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}